version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: the_dump_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - the-dump-net

  elasticsearch:
    image: elasticsearch:7.17.10 # Versão estável e compatível com o cliente Python
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" # Ajuste para usar menos RAM
    ports:
      - "9200:9200"
      - "9300:9300"